# Generated by Django 5.2.7 on 2025-10-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este email'}, max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(help_text='Nombre único para la URL del perfil', max_length=50, unique=True, verbose_name='nombre de usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='apellidos')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('artisan', 'Artesano'), ('artist', 'Artista'), ('customer', 'Cliente')], default='artisan', max_length=20, verbose_name='rol')),
                ('is_approved', models.BooleanField(default=False, help_text='Los artesanos necesitan aprobación manual antes de poder vender.', verbose_name='aprobado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'), models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'), models.Index(fields=['role', 'is_approved'], name='accounts_us_role_2798cb_idx')],
            },
        ),
    ]
