# Generated by Django 5.2.7 on 2025-10-25 18:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Número único de orden generado automáticamente (ORD-YYYYMMDD-XXXXXX)', max_length=50, unique=True)),
                ('customer_email', models.EmailField(help_text='Email del comprador invitado para confirmación y seguimiento', max_length=254)),
                ('customer_name', models.CharField(help_text='Nombre completo del comprador', max_length=200)),
                ('customer_phone', models.CharField(blank=True, help_text='Teléfono de contacto opcional', max_length=20)),
                ('shipping_address', models.TextField(help_text='Dirección de envío completa (calle, número, piso)')),
                ('shipping_city', models.CharField(help_text='Ciudad o población', max_length=100)),
                ('shipping_postal_code', models.CharField(help_text='Código postal', max_length=20)),
                ('shipping_country', models.CharField(default='España', help_text='País de envío', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado actual del pedido', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado del pago', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total del pedido en EUR (calculado automáticamente)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del comprador (ej: instrucciones de entrega)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del pedido')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'), models.Index(fields=['customer_email'], name='orders_orde_custome_ca0107_idx'), models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'), models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nombre del producto en el momento de compra (snapshot)', max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Precio unitario en el momento de compra (snapshot)', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades compradas')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal = precio x cantidad (calculado automáticamente)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del item')),
                ('artisan', models.ForeignKey(help_text='Artesano vendedor (desnormalizado para queries eficientes)', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='artisans.artisanprofile')),
                ('order', models.ForeignKey(help_text='Pedido al que pertenece este artículo', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Producto comprado (PROTECT para mantener historial)', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Artículo de pedido',
                'verbose_name_plural': 'Artículos de pedido',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'), models.Index(fields=['artisan', '-created_at'], name='orders_orde_artisan_accf71_idx'), models.Index(fields=['product'], name='orders_orde_product_32ff41_idx')],
            },
        ),
    ]
