# Generated by Django 5.0.1 on 2025-10-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado del pago', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
    ]
