services:
  postgres:
    image: postgres:15-alpine
    container_name: mitaller_db
    environment:
      POSTGRES_DB: mitaller_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: