# Generated by Django 5.0.1 on 2025-10-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto, materiales, dimensiones, etc.', verbose_name='descripción')),
                ('category', models.CharField(choices=[('ceramics', 'Cerámica'), ('jewelry', 'Joyería'), ('leather', 'Marroquinería'), ('textiles', 'Textiles'), ('wood', 'Madera'), ('glass', 'Vidrio'), ('home_decor', 'Decoración Hogar'), ('accessories', 'Accesorios'), ('other', 'Otro')], help_text='Categoría del producto artesanal', max_length=20, verbose_name='categoría')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en EUR', max_digits=10, verbose_name='precio')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='stock')),
                ('thumbnail_url', models.URLField(help_text='URL de imagen principal almacenada en Cloudinary', max_length=500, verbose_name='URL imagen principal')),
                ('images', models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales almacenadas en Cloudinary', verbose_name='URLs galería')),
                ('is_active', models.BooleanField(default=True, help_text='Producto visible y disponible en la tienda', verbose_name='activo')),
                ('stripe_product_id', models.CharField(blank=True, help_text='ID del producto en Stripe (ej: prod_xxx)', max_length=100, null=True, verbose_name='ID producto Stripe')),
                ('stripe_price_id', models.CharField(blank=True, help_text='ID del precio en Stripe (ej: price_xxx)', max_length=100, null=True, verbose_name='ID precio Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('artist', models.ForeignKey(help_text='Artesano vendedor de este producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='artists.artistprofile', verbose_name='artesano')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist', 'is_active'], name='shop_produc_artist__6bda49_idx'), models.Index(fields=['artist', 'category'], name='shop_produc_artist__3a497d_idx'), models.Index(fields=['is_active', '-created_at'], name='shop_produc_is_acti_1ba9a0_idx')],
            },
        ),
    ]
