# Generated by Django 5.2.7 on 2025-10-29 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_update_artisan_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Producto destacado por el artesano', verbose_name='destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_available',
            field=models.BooleanField(default=True, help_text='Permite recoger en taller', verbose_name='recogida disponible'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', '-created_at'], name='shop_produc_is_feat_a0fca9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['artisan', 'is_featured', '-created_at'], name='shop_produc_artisan_343171_idx'),
        ),
    ]
