# Generated by Django 5.2.7 on 2025-10-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL única del creador', max_length=100, unique=True, verbose_name='slug')),
                ('bio', models.TextField(blank=True, help_text='Descripción del creador y su trabajo', verbose_name='biografía')),
                ('avatar', models.URLField(blank=True, help_text='URL de foto de perfil almacenada en Cloudinary', max_length=500, null=True, verbose_name='avatar')),
                ('cover_image', models.URLField(blank=True, help_text='URL de imagen de portada almacenada en Cloudinary', max_length=500, null=True, verbose_name='imagen de portada')),
                ('website', models.URLField(blank=True, help_text='URL del sitio web personal', verbose_name='sitio web')),
                ('instagram', models.CharField(blank=True, help_text='Usuario de Instagram (sin @)', max_length=100, verbose_name='instagram')),
                ('facebook', models.CharField(blank=True, help_text='Usuario de Facebook', max_length=100, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, help_text='Usuario de Twitter (sin @)', max_length=100, verbose_name='twitter')),
                ('city', models.CharField(blank=True, help_text='Ciudad donde reside o trabaja', max_length=100, verbose_name='ciudad')),
                ('country', models.CharField(default='España', help_text='País de residencia', max_length=100, verbose_name='país')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('discipline', models.CharField(blank=True, choices=[('painting', 'Pintura'), ('sculpture', 'Escultura'), ('photography', 'Fotografía'), ('digital_art', 'Arte Digital'), ('music', 'Música'), ('dance', 'Danza'), ('theater', 'Teatro'), ('performance', 'Performance'), ('mixed_media', 'Técnica Mixta'), ('other', 'Otro')], help_text='Disciplina artística principal', max_length=50, verbose_name='disciplina')),
                ('exhibition_history', models.TextField(blank=True, help_text='Exposiciones y eventos en los que ha participado', verbose_name='historial de exposiciones')),
                ('awards', models.TextField(blank=True, help_text='Premios y reconocimientos recibidos', verbose_name='premios')),
                ('available_for_commissions', models.BooleanField(default=False, help_text='Acepta encargos personalizados', verbose_name='disponible para encargos')),
                ('available_for_events', models.BooleanField(default=False, help_text='Disponible para eventos (conciertos, actuaciones)', verbose_name='disponible para eventos')),
                ('base_price_range', models.CharField(blank=True, help_text='Ejemplo: €500-€2000', max_length=50, verbose_name='rango de precios base')),
                ('user', models.OneToOneField(help_text='Usuario asociado a este perfil de artista', on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Artist Profile',
                'verbose_name_plural': 'Artist Profiles',
            },
        ),
    ]
