# Generated by Django 5.0.1 on 2025-10-12 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL única del artesano: /artistas/{slug}/', max_length=100, unique=True, verbose_name='slug')),
                ('display_name', models.CharField(help_text='Nombre que aparece públicamente', max_length=150, verbose_name='nombre público')),
                ('bio', models.TextField(blank=True, help_text='Descripción del artesano y su trabajo', verbose_name='biografía')),
                ('craft_type', models.CharField(choices=[('ceramics', 'Cerámica'), ('jewelry', 'Joyería'), ('leather', 'Marroquinería'), ('textiles', 'Textiles'), ('wood', 'Madera'), ('glass', 'Vidrio'), ('other', 'Otro')], help_text='Especialidad principal del artesano', max_length=20, verbose_name='tipo de artesanía')),
                ('location', models.CharField(choices=[('mao', 'Maó'), ('ciutadella', 'Ciutadella'), ('alaior', 'Alaior'), ('es_castell', 'Es Castell'), ('ferreries', 'Ferreries'), ('es_mercadal', 'Es Mercadal'), ('es_migjorn', 'Es Migjorn Gran'), ('sant_lluis', 'Sant Lluís'), ('other', 'Otro')], help_text='Municipio donde se encuentra el taller', max_length=20, verbose_name='ubicación')),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del artesano', null=True, upload_to='artists/avatars/', verbose_name='avatar')),
                ('cover_image', models.ImageField(blank=True, help_text='Imagen de portada del perfil', null=True, upload_to='artists/covers/', verbose_name='imagen de portada')),
                ('website', models.URLField(blank=True, help_text='URL del sitio web personal', null=True, verbose_name='sitio web')),
                ('instagram', models.CharField(blank=True, help_text='Usuario de Instagram (sin @)', max_length=100, null=True, verbose_name='instagram')),
                ('facebook', models.URLField(blank=True, help_text='URL de página de Facebook', null=True, verbose_name='facebook')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='teléfono')),
                ('stripe_account_id', models.CharField(blank=True, help_text='ID de cuenta Stripe Connect para pagos', max_length=100, null=True, verbose_name='ID cuenta Stripe')),
                ('stripe_onboarding_completed', models.BooleanField(default=False, help_text='Indica si completó el proceso de onboarding en Stripe', verbose_name='onboarding Stripe completado')),
                ('total_works', models.IntegerField(default=0, help_text='Número total de obras en portfolio', verbose_name='total obras')),
                ('total_products', models.IntegerField(default=0, help_text='Número total de productos en venta', verbose_name='total productos')),
                ('is_featured', models.BooleanField(default=False, help_text='Artesano destacado en la página principal', verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.OneToOneField(help_text='Usuario asociado a este perfil de artesano', on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de artesano',
                'verbose_name_plural': 'perfiles de artesanos',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='artists_art_slug_0ebf1d_idx'), models.Index(fields=['location'], name='artists_art_locatio_23c2e3_idx'), models.Index(fields=['craft_type'], name='artists_art_craft_t_2ab9dd_idx'), models.Index(fields=['-is_featured', '-created_at'], name='artists_art_is_feat_e889c0_idx')],
            },
        ),
    ]
