# Generated by Django 5.0.1 on 2025-10-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_account_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('restricted', 'Restringida'), ('disabled', 'Deshabilitada')], default='pending', help_text='Estado de la cuenta Stripe', max_length=20, verbose_name='estado cuenta Stripe'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False, help_text='Si puede recibir pagos', verbose_name='pagos habilitados'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_onboarding_url',
            field=models.TextField(blank=True, help_text='URL de onboarding Stripe temporal', null=True, verbose_name='URL onboarding Stripe'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Si puede recibir transferencias', verbose_name='transferencias habilitadas'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID de cuenta Stripe Connect', max_length=255, null=True, unique=True, verbose_name='ID cuenta Stripe'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False, help_text='Si completó onboarding Stripe', verbose_name='onboarding Stripe completado'),
        ),
    ]
