# Generated by Django 5.2.7 on 2025-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artistprofile_stripe_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL de foto de perfil almacenada en Cloudinary', max_length=500, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL de imagen de portada almacenada en Cloudinary', max_length=500, null=True, verbose_name='imagen de portada'),
        ),
    ]
