# Generated by Django 5.2.7 on 2025-10-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_change_image_fields_to_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='facebook',
        ),
    ]
