# Generated by Django 5.2.7 on 2025-10-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL única del creador', max_length=100, unique=True, verbose_name='slug')),
                ('bio', models.TextField(blank=True, help_text='Descripción del creador y su trabajo', verbose_name='biografía')),
                ('avatar', models.URLField(blank=True, help_text='URL de foto de perfil almacenada en Cloudinary', max_length=500, null=True, verbose_name='avatar')),
                ('cover_image', models.URLField(blank=True, help_text='URL de imagen de portada almacenada en Cloudinary', max_length=500, null=True, verbose_name='imagen de portada')),
                ('website', models.URLField(blank=True, help_text='URL del sitio web personal', verbose_name='sitio web')),
                ('instagram', models.CharField(blank=True, help_text='Usuario de Instagram (sin @)', max_length=100, verbose_name='instagram')),
                ('facebook', models.CharField(blank=True, help_text='Usuario de Facebook', max_length=100, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, help_text='Usuario de Twitter (sin @)', max_length=100, verbose_name='twitter')),
                ('city', models.CharField(blank=True, help_text='Ciudad donde reside o trabaja', max_length=100, verbose_name='ciudad')),
                ('country', models.CharField(default='España', help_text='País de residencia', max_length=100, verbose_name='país')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('display_name', models.CharField(help_text='Nombre que aparece públicamente', max_length=150, verbose_name='nombre público')),
                ('craft_type', models.CharField(choices=[('ceramics', 'Cerámica'), ('jewelry', 'Joyería'), ('leather', 'Marroquinería'), ('textiles', 'Textiles'), ('wood', 'Madera'), ('glass', 'Vidrio'), ('other', 'Otro')], help_text='Especialidad principal del artesano', max_length=20, verbose_name='tipo de artesanía')),
                ('location', models.CharField(choices=[('mao', 'Maó'), ('ciutadella', 'Ciutadella'), ('alaior', 'Alaior'), ('es_castell', 'Es Castell'), ('ferreries', 'Ferreries'), ('es_mercadal', 'Es Mercadal'), ('es_migjorn', 'Es Migjorn Gran'), ('sant_lluis', 'Sant Lluís'), ('other', 'Otro')], help_text='Municipio donde se encuentra el taller', max_length=20, verbose_name='ubicación')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='teléfono')),
                ('stripe_account_id', models.CharField(blank=True, help_text='ID de cuenta Stripe Connect', max_length=255, null=True, unique=True, verbose_name='ID cuenta Stripe')),
                ('stripe_account_status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('restricted', 'Restringida'), ('disabled', 'Deshabilitada')], default='pending', help_text='Estado de la cuenta Stripe', max_length=20, verbose_name='estado cuenta Stripe')),
                ('stripe_onboarding_completed', models.BooleanField(default=False, help_text='Si completó onboarding Stripe', verbose_name='onboarding Stripe completado')),
                ('stripe_charges_enabled', models.BooleanField(default=False, help_text='Si puede recibir pagos', verbose_name='pagos habilitados')),
                ('stripe_payouts_enabled', models.BooleanField(default=False, help_text='Si puede recibir transferencias', verbose_name='transferencias habilitadas')),
                ('stripe_onboarding_url', models.TextField(blank=True, help_text='URL de onboarding Stripe temporal', null=True, verbose_name='URL onboarding Stripe')),
                ('total_works', models.IntegerField(default=0, help_text='Número total de obras en portfolio', verbose_name='total obras')),
                ('total_products', models.IntegerField(default=0, help_text='Número total de productos en venta', verbose_name='total productos')),
                ('is_featured', models.BooleanField(default=False, help_text='Artesano destacado en la página principal', verbose_name='destacado')),
                ('user', models.OneToOneField(help_text='Usuario asociado a este perfil de artesano', on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de artesano',
                'verbose_name_plural': 'perfiles de artesanos',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='artisans_ar_slug_5bf618_idx'), models.Index(fields=['location'], name='artisans_ar_locatio_ec0ab7_idx'), models.Index(fields=['craft_type'], name='artisans_ar_craft_t_16dd8d_idx'), models.Index(fields=['-is_featured', '-created_at'], name='artisans_ar_is_feat_c1b3b7_idx')],
            },
        ),
    ]
