# Generated by Django 5.2.7 on 2025-10-29 16:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Ej: "Llamar 30min antes de venir"', verbose_name='instrucciones de recogida'),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Tarifa fija de envío del artesano (EUR)', max_digits=10, verbose_name='coste de envío'),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='workshop_address',
            field=models.TextField(blank=True, help_text='Dirección completa para recogida en taller', verbose_name='dirección del taller'),
        ),
    ]
