# Generated by Django 5.2.7 on 2025-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisanprofile_pickup_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='short_description',
            field=models.CharField(blank=True, help_text='Texto breve que aparece en el hero del perfil (1-2 líneas)', max_length=200, verbose_name='descripción corta'),
        ),
    ]
