# Generated by Django 5.0.1 on 2025-10-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_artistprofile_stripe_account_status_and_more'),
        ('orders', '0002_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto total en EUR', max_digits=10, verbose_name='Monto total')),
                ('marketplace_fee', models.DecimalField(decimal_places=2, help_text='Comisión del marketplace en EUR', max_digits=10, verbose_name='Comisión marketplace')),
                ('artist_amount', models.DecimalField(decimal_places=2, help_text='Monto para el artesano en EUR', max_digits=10, verbose_name='Monto artesano')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado actual del pago', max_length=20, verbose_name='Estado')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID del PaymentIntent en Stripe', max_length=255, null=True, unique=True, verbose_name='PaymentIntent ID')),
                ('stripe_charge_id', models.CharField(blank=True, help_text='ID del Charge en Stripe', max_length=255, null=True, verbose_name='Charge ID')),
                ('stripe_transfer_id', models.CharField(blank=True, help_text='ID del Transfer al artesano', max_length=255, null=True, verbose_name='Transfer ID')),
                ('failure_message', models.TextField(blank=True, help_text='Mensaje de error si el pago falló', null=True, verbose_name='Mensaje de error')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional del pago', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha cuando se completó el pago', null=True, verbose_name='Fecha de pago')),
                ('artist', models.ForeignKey(help_text='Artesano que recibe el pago (desnormalizado para queries)', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='artists.artistprofile', verbose_name='Artesano')),
                ('order', models.OneToOneField(help_text='Pedido asociado a este pago', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'), models.Index(fields=['artist'], name='payments_pa_artist__157caa_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'), models.Index(fields=['-created_at'], name='payments_pa_created_3147e3_idx')],
            },
        ),
    ]
