# Generated by Django 5.2.7 on 2025-10-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la obra', max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la obra, técnica, materiales, proceso, etc.', verbose_name='descripción')),
                ('category', models.CharField(blank=True, choices=[('ceramics', 'Cerámica'), ('jewelry', 'Joyería'), ('leather', 'Marroquinería'), ('textiles', 'Textiles'), ('wood', 'Madera'), ('glass', 'Vidrio'), ('sculpture', 'Escultura'), ('painting', 'Pintura'), ('other', 'Otro')], help_text='Categoría o tipo de obra artística', max_length=20, null=True, verbose_name='categoría')),
                ('thumbnail_url', models.URLField(help_text='URL de imagen principal almacenada en Cloudinary', max_length=500, verbose_name='imagen principal')),
                ('images', models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales almacenadas en Cloudinary', verbose_name='galería de imágenes')),
                ('display_order', models.IntegerField(default=0, help_text='Orden de visualización en el portfolio (menor = primero). Permite drag & drop.', verbose_name='orden de visualización')),
                ('is_featured', models.BooleanField(default=False, help_text='Obra destacada que aparece prominentemente en el perfil', verbose_name='destacada')),
                ('is_active', models.BooleanField(default=True, help_text='Obra activa y visible públicamente. Permite ocultar obras sin eliminarlas.', verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('artisan', models.ForeignKey(help_text='Artesano creador de esta obra', limit_choices_to={'role': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='artesano')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['artisan', 'display_order', '-created_at'],
                'indexes': [models.Index(fields=['artisan', 'display_order'], name='works_work_artisan_b4aa2c_idx'), models.Index(fields=['category'], name='works_work_categor_2675d5_idx'), models.Index(fields=['is_featured', '-created_at'], name='works_work_is_feat_86bf57_idx')],
            },
        ),
    ]
