# Generated by Django 5.2.7 on 2025-10-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Obra activa y visible públicamente. Permite ocultar obras sin eliminarlas.', verbose_name='activa'),
        ),
    ]
